export const SEARCH_FOCUS = 'header/search_focus'
export const SEARCH_BLUR = 'header/search_blur'
export const CHANGE_LIST = 'header/change_list'
export const MOUSEENTER = 'header/mouse_enter'
export const MOUSELEAVE = 'header/mouse_leave'
export const PAGEVALUE = 'header/page_value'